version: '3.7'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
      - ./sentence_transformers_cache:/root/.cache/torch/sentence_transformers
    command: streamlit run app.py
    ports:
      - "127.0.0.1:7888:8501"
    deploy:
      resources:
        limits:
          memory: 500M
    environment:
      VIRTUAL_HOST: inndex.janczechowski.com
      VIRTUAL_PORT: 8501
      LETSENCRYPT_HOST: inndex.janczechowski.com
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
