version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: streamlit run app.py
    environment:
      VIRTUAL_HOST: inndex.janczechowski.com
      VIRTUAL_PORT: 8501
      LETSENCRYPT_HOST: inndex.janczechowski.com
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
